package modelo;
// Generated 11/04/2016 03:54:24 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Automovil generated by hbm2java
 */
public class Automovil implements java.io.Serializable {

    private int idAutomovil;
    private Chofer chofer;
    private String noIdentificacion;
    private String modelo;
    private String placa;
    private String color;
    private int capacidad;
    private Set rutas = new HashSet(0);

    public Automovil() {
    }

    public Automovil(Chofer chofer, String noIdentificacion, String modelo, String placa, String color, int capacidad) {
        this.chofer = chofer;
        this.noIdentificacion = noIdentificacion;
        this.modelo = modelo;
        this.placa = placa;
        this.color = color;
        this.capacidad = capacidad;
    }

    public Automovil(Chofer chofer, String noIdentificacion, String modelo, String placa, String color, int capacidad, Set rutas) {
        this.chofer = chofer;
        this.noIdentificacion = noIdentificacion;
        this.modelo = modelo;
        this.placa = placa;
        this.color = color;
        this.capacidad = capacidad;
        this.rutas = rutas;
    }

    public int getCapacidad() {
        return capacidad;
    }

    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

    public int getIdAutomovil() {
        return this.idAutomovil;
    }

    public void setIdAutomovil(int idAutomovil) {
        this.idAutomovil = idAutomovil;

    }

    public Chofer getChofer() {
        return this.chofer;
    }

    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

    public String getNoIdentificacion() {
        return this.noIdentificacion;
    }

    public void setNoIdentificacion(String noIdentificacion) {
        this.noIdentificacion = noIdentificacion;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getPlaca() {
        return this.placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Set getRutas() {
        return this.rutas;
    }

    public void setRutas(Set rutas) {
        this.rutas = rutas;
    }

}
