package modelo;
// Generated May 16, 2016 9:29:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Boletin generated by hbm2java
 */
@Entity
@Table(name = "boletin", schema = "public"
)
public class Boletin implements java.io.Serializable {

    private int idBoletin;
    private Ruta ruta;
    private String titulo;
    private String contenido;
    private Date fecha;

    public Boletin() {
    }

    public Boletin(int idBoletin, Ruta ruta, String titulo, String contenido, Date fecha) {
        this.idBoletin = idBoletin;
        this.ruta = ruta;
        this.titulo = titulo;
        this.contenido = contenido;
        this.fecha = fecha;
    }

    @Id

    @Column(name = "id_boletin", unique = true, nullable = false)
    public int getIdBoletin() {
        return this.idBoletin;
    }

    public void setIdBoletin(int idBoletin) {
        this.idBoletin = idBoletin;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_ruta", nullable = false)
    public Ruta getRuta() {
        return this.ruta;
    }

    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }

    @Column(name = "titulo", nullable = false, length = 128)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "contenido", nullable = false)
    public String getContenido() {
        return this.contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 29)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
