package modelo;
// Generated May 17, 2016 4:03:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Chofer generated by hbm2java
 */
@Entity
@Table(name = "chofer", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = "ccorreo"),
    @UniqueConstraint(columnNames = "cno_cuenta"),
    @UniqueConstraint(columnNames = "cno_id")}
)
public class Chofer implements java.io.Serializable {

    private int idChofer;
    private String cnombre;
    private String capp;
    private String capm;
    private String ccorreo;
    private String cnoCuenta;
    private String cnoId;
    private Date cfechaNac;
    private String ccontrasenia;
    private Set calificacionPasajeros = new HashSet(0);
    private Set mensajePasajeros = new HashSet(0);
    private Set calificacionChofers = new HashSet(0);
    private Set mensajeChofers = new HashSet(0);
    private Set perfilChofers = new HashSet(0);
    private Set automovils = new HashSet(0);
    private Set notificacionChofers = new HashSet(0);

    public Chofer() {
    }

    public Chofer(int idChofer, String cnombre, String capp, String capm, String ccorreo, String cnoCuenta, String cnoId, Date cfechaNac, String ccontrasenia) {
        this.idChofer = idChofer;
        this.cnombre = cnombre;
        this.capp = capp;
        this.capm = capm;
        this.ccorreo = ccorreo;
        this.cnoCuenta = cnoCuenta;
        this.cnoId = cnoId;
        this.cfechaNac = cfechaNac;
        this.ccontrasenia = ccontrasenia;
    }

    public Chofer(int idChofer, String cnombre, String capp, String capm, String ccorreo, String cnoCuenta, String cnoId, Date cfechaNac, String ccontrasenia, Set calificacionPasajeros, Set mensajePasajeros, Set calificacionChofers, Set mensajeChofers, Set perfilChofers, Set automovils, Set notificacionChofers) {
        this.idChofer = idChofer;
        this.cnombre = cnombre;
        this.capp = capp;
        this.capm = capm;
        this.ccorreo = ccorreo;
        this.cnoCuenta = cnoCuenta;
        this.cnoId = cnoId;
        this.cfechaNac = cfechaNac;
        this.ccontrasenia = ccontrasenia;
        this.calificacionPasajeros = calificacionPasajeros;
        this.mensajePasajeros = mensajePasajeros;
        this.calificacionChofers = calificacionChofers;
        this.mensajeChofers = mensajeChofers;
        this.perfilChofers = perfilChofers;
        this.automovils = automovils;
        this.notificacionChofers = notificacionChofers;
    }

    @Id

    @Column(name = "id_chofer", unique = true, nullable = false)
    public int getIdChofer() {
        return this.idChofer;
    }

    public void setIdChofer(int idChofer) {
        this.idChofer = idChofer;
    }

    @Column(name = "cnombre", nullable = false, length = 64)
    public String getCnombre() {
        return this.cnombre;
    }

    public void setCnombre(String cnombre) {
        this.cnombre = cnombre;
    }

    @Column(name = "capp", nullable = false, length = 64)
    public String getCapp() {
        return this.capp;
    }

    public void setCapp(String capp) {
        this.capp = capp;
    }

    @Column(name = "capm", nullable = false, length = 64)
    public String getCapm() {
        return this.capm;
    }

    public void setCapm(String capm) {
        this.capm = capm;
    }

    @Column(name = "ccorreo", unique = true, nullable = false, length = 128)
    public String getCcorreo() {
        return this.ccorreo;
    }

    public void setCcorreo(String ccorreo) {
        this.ccorreo = ccorreo;
    }

    @Column(name = "cno_cuenta", unique = true, nullable = false, length = 9)
    public String getCnoCuenta() {
        return this.cnoCuenta;
    }

    public void setCnoCuenta(String cnoCuenta) {
        this.cnoCuenta = cnoCuenta;
    }

    @Column(name = "cno_id", unique = true, nullable = false, length = 64)
    public String getCnoId() {
        return this.cnoId;
    }

    public void setCnoId(String cnoId) {
        this.cnoId = cnoId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "cfecha_nac", nullable = false, length = 13)
    public Date getCfechaNac() {
        return this.cfechaNac;
    }

    public void setCfechaNac(Date cfechaNac) {
        this.cfechaNac = cfechaNac;
    }

    @Column(name = "ccontrasenia", nullable = false, length = 128)
    public String getCcontrasenia() {
        return this.ccontrasenia;
    }

    public void setCcontrasenia(String ccontrasenia) {
        this.ccontrasenia = ccontrasenia;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getCalificacionPasajeros() {
        return this.calificacionPasajeros;
    }

    public void setCalificacionPasajeros(Set calificacionPasajeros) {
        this.calificacionPasajeros = calificacionPasajeros;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getMensajePasajeros() {
        return this.mensajePasajeros;
    }

    public void setMensajePasajeros(Set mensajePasajeros) {
        this.mensajePasajeros = mensajePasajeros;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getCalificacionChofers() {
        return this.calificacionChofers;
    }

    public void setCalificacionChofers(Set calificacionChofers) {
        this.calificacionChofers = calificacionChofers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getMensajeChofers() {
        return this.mensajeChofers;
    }

    public void setMensajeChofers(Set mensajeChofers) {
        this.mensajeChofers = mensajeChofers;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "chofer")
    public Set getPerfilChofers() {
        return this.perfilChofers;
    }

    public void setPerfilChofers(Set perfilChofers) {
        this.perfilChofers = perfilChofers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getAutomovils() {
        return this.automovils;
    }

    public void setAutomovils(Set automovils) {
        this.automovils = automovils;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getNotificacionChofers() {
        return this.notificacionChofers;
    }

    public void setNotificacionChofers(Set notificacionChofers) {
        this.notificacionChofers = notificacionChofers;
    }

}
