package modelo;
// Generated May 7, 2016 1:06:44 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Chofer generated by hbm2java
 */
@Entity
@Table(name = "chofer", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = "ccorreo"),
    @UniqueConstraint(columnNames = "cno_cuenta"),
    @UniqueConstraint(columnNames = "cno_id")}
)
public class Chofer implements java.io.Serializable {

    private int idChofer;
    private String cnombre;
    private String capp;
    private String capm;
    private String ccorreo;
    private String cnoCuenta;
    private String cnoId;
    private Date cfechaNac;
    private String ccontrasenia;
    private Set perfilChofers = new HashSet(0);
    private Set automovils = new HashSet(0);

    public Chofer() {
    }

    public Chofer(int idChofer, String cnombre, String capp, String capm, String ccorreo, String cnoCuenta, String cnoId, Date cfechaNac, String ccontrasenia) {
        this.idChofer = idChofer;
        this.cnombre = cnombre;
        this.capp = capp;
        this.capm = capm;
        this.ccorreo = ccorreo;
        this.cnoCuenta = cnoCuenta;
        this.cnoId = cnoId;
        this.cfechaNac = cfechaNac;
        this.ccontrasenia = ccontrasenia;
    }

    public Chofer(int idChofer, String cnombre, String capp, String capm, String ccorreo, String cnoCuenta, String cnoId, Date cfechaNac, String ccontrasenia, Set perfilChofers, Set automovils) {
        this.idChofer = idChofer;
        this.cnombre = cnombre;
        this.capp = capp;
        this.capm = capm;
        this.ccorreo = ccorreo;
        this.cnoCuenta = cnoCuenta;
        this.cnoId = cnoId;
        this.cfechaNac = cfechaNac;
        this.ccontrasenia = ccontrasenia;
        this.perfilChofers = perfilChofers;
        this.automovils = automovils;
    }

    @Id

    @Column(name = "id_chofer", unique = true, nullable = false)
    public int getIdChofer() {
        return this.idChofer;
    }

    public void setIdChofer(int idChofer) {
        this.idChofer = idChofer;
    }

    @Column(name = "cnombre", nullable = false, length = 64)
    public String getCnombre() {
        return this.cnombre;
    }

    public void setCnombre(String cnombre) {
        this.cnombre = cnombre;
    }

    @Column(name = "capp", nullable = false, length = 64)
    public String getCapp() {
        return this.capp;
    }

    public void setCapp(String capp) {
        this.capp = capp;
    }

    @Column(name = "capm", nullable = false, length = 64)
    public String getCapm() {
        return this.capm;
    }

    public void setCapm(String capm) {
        this.capm = capm;
    }

    @Column(name = "ccorreo", unique = true, nullable = false, length = 128)
    public String getCcorreo() {
        return this.ccorreo;
    }

    public void setCcorreo(String ccorreo) {
        this.ccorreo = ccorreo;
    }

    @Column(name = "cno_cuenta", unique = true, nullable = false, length = 9)
    public String getCnoCuenta() {
        return this.cnoCuenta;
    }

    public void setCnoCuenta(String cnoCuenta) {
        this.cnoCuenta = cnoCuenta;
    }

    @Column(name = "cno_id", unique = true, nullable = false, length = 64)
    public String getCnoId() {
        return this.cnoId;
    }

    public void setCnoId(String cnoId) {
        this.cnoId = cnoId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "cfecha_nac", nullable = false, length = 13)
    public Date getCfechaNac() {
        return this.cfechaNac;
    }

    public void setCfechaNac(Date cfechaNac) {
        this.cfechaNac = cfechaNac;
    }

    @Column(name = "ccontrasenia", nullable = false, length = 128)
    public String getCcontrasenia() {
        return this.ccontrasenia;
    }

    public void setCcontrasenia(String ccontrasenia) {
        this.ccontrasenia = ccontrasenia;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "chofer")
    public Set getPerfilChofers() {
        return this.perfilChofers;
    }

    public void setPerfilChofers(Set perfilChofers) {
        this.perfilChofers = perfilChofers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "chofer")
    public Set getAutomovils() {
        return this.automovils;
    }

    public void setAutomovils(Set automovils) {
        this.automovils = automovils;
    }

}
