package modelo;
// Generated May 4, 2016 9:25:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

    private int idHorario;
    private Ruta ruta;
    private Date lunes;
    private Date martes;
    private Date miercoles;
    private Date jueves;
    private Date viernes;
    private Date sabado;

    public Horario() {
    }

    public Horario(Ruta ruta) {
        this.ruta = ruta;
    }

    public Horario(Ruta ruta, Date lunes, Date martes, Date miercoles, Date jueves, Date viernes, Date sabado) {
        this.ruta = ruta;
        this.lunes = lunes;
        this.martes = martes;
        this.miercoles = miercoles;
        this.jueves = jueves;
        this.viernes = viernes;
        this.sabado = sabado;
    }

    public int getIdHorario() {
        return this.idHorario;
    }

    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }

    public Ruta getRuta() {
        return this.ruta;
    }

    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }

    public Date getLunes() {
        return this.lunes;
    }

    public void setLunes(Date lunes) {
        this.lunes = lunes;
    }

    public Date getMartes() {
        return this.martes;
    }

    public void setMartes(Date martes) {
        this.martes = martes;
    }

    public Date getMiercoles() {
        return this.miercoles;
    }

    public void setMiercoles(Date miercoles) {
        this.miercoles = miercoles;
    }

    public Date getJueves() {
        return this.jueves;
    }

    public void setJueves(Date jueves) {
        this.jueves = jueves;
    }

    public Date getViernes() {
        return this.viernes;
    }

    public void setViernes(Date viernes) {
        this.viernes = viernes;
    }

    public Date getSabado() {
        return this.sabado;
    }

    public void setSabado(Date sabado) {
        this.sabado = sabado;
    }

}
