package modelo;
// Generated May 7, 2016 1:06:44 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id_ruta")
)
public class Horario implements java.io.Serializable {

    private int idHorario;
    private Ruta ruta;
    private Date lunes;
    private Date martes;
    private Date miercoles;
    private Date jueves;
    private Date viernes;
    private Date sabado;

    public Horario() {
    }

    public Horario(int idHorario, Ruta ruta) {
        this.idHorario = idHorario;
        this.ruta = ruta;
    }

    public Horario(int idHorario, Ruta ruta, Date lunes, Date martes, Date miercoles, Date jueves, Date viernes, Date sabado) {
        this.idHorario = idHorario;
        this.ruta = ruta;
        this.lunes = lunes;
        this.martes = martes;
        this.miercoles = miercoles;
        this.jueves = jueves;
        this.viernes = viernes;
        this.sabado = sabado;
    }

    @Id

    @Column(name = "id_horario", unique = true, nullable = false)
    public int getIdHorario() {
        return this.idHorario;
    }

    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_ruta", unique = true, nullable = false)
    public Ruta getRuta() {
        return this.ruta;
    }

    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "lunes", length = 15)
    public Date getLunes() {
        return this.lunes;
    }

    public void setLunes(Date lunes) {
        this.lunes = lunes;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "martes", length = 15)
    public Date getMartes() {
        return this.martes;
    }

    public void setMartes(Date martes) {
        this.martes = martes;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "miercoles", length = 15)
    public Date getMiercoles() {
        return this.miercoles;
    }

    public void setMiercoles(Date miercoles) {
        this.miercoles = miercoles;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "jueves", length = 15)
    public Date getJueves() {
        return this.jueves;
    }

    public void setJueves(Date jueves) {
        this.jueves = jueves;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "viernes", length = 15)
    public Date getViernes() {
        return this.viernes;
    }

    public void setViernes(Date viernes) {
        this.viernes = viernes;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "sabado", length = 15)
    public Date getSabado() {
        return this.sabado;
    }

    public void setSabado(Date sabado) {
        this.sabado = sabado;
    }

}
