package modelo;
// Generated May 16, 2016 1:45:53 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MensajePasajero generated by hbm2java
 */
@Entity
@Table(name = "mensaje_pasajero", schema = "public"
)
public class MensajePasajero implements java.io.Serializable {

    private int idMensajep;
    private Chofer chofer;
    private Pasajero pasajero;
    private String asunto;
    private String contenido;
    private Date fecha;

    public MensajePasajero() {
    }

    public MensajePasajero(int idMensajep, Chofer chofer, Pasajero pasajero, String asunto, String contenido, Date fecha) {
        this.idMensajep = idMensajep;
        this.chofer = chofer;
        this.pasajero = pasajero;
        this.asunto = asunto;
        this.contenido = contenido;
        this.fecha = fecha;
    }

    @Id

    @Column(name = "id_mensajep", unique = true, nullable = false)
    public int getIdMensajep() {
        return this.idMensajep;
    }

    public void setIdMensajep(int idMensajep) {
        this.idMensajep = idMensajep;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_chofer", nullable = false)
    public Chofer getChofer() {
        return this.chofer;
    }

    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pasajero", nullable = false)
    public Pasajero getPasajero() {
        return this.pasajero;
    }

    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }

    @Column(name = "asunto", nullable = false, length = 64)
    public String getAsunto() {
        return this.asunto;
    }

    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    @Column(name = "contenido", nullable = false)
    public String getContenido() {
        return this.contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 29)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
