package modelo;
// Generated May 18, 2016 12:59:04 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotificacionChofer generated by hbm2java
 */
@Entity
@Table(name = "notificacion_chofer", schema = "public"
)
public class NotificacionChofer implements java.io.Serializable {

    private int idNotificacionc;
    private Chofer chofer;
    private String titulo;
    private String contenido;
    private Date fecha;
    private boolean visto;

    public NotificacionChofer() {
    }

    public NotificacionChofer(int idNotificacionc, Chofer chofer, String titulo, String contenido, Date fecha, boolean visto) {
        this.idNotificacionc = idNotificacionc;
        this.chofer = chofer;
        this.titulo = titulo;
        this.contenido = contenido;
        this.fecha = fecha;
        this.visto = visto;
    }

    @Id

    @Column(name = "id_notificacionc", unique = true, nullable = false)
    public int getIdNotificacionc() {
        return this.idNotificacionc;
    }

    public void setIdNotificacionc(int idNotificacionc) {
        this.idNotificacionc = idNotificacionc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_chofer", nullable = false)
    public Chofer getChofer() {
        return this.chofer;
    }

    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

    @Column(name = "titulo", nullable = false, length = 64)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "contenido", nullable = false, length = 256)
    public String getContenido() {
        return this.contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 29)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "visto", nullable = false)
    public boolean isVisto() {
        return this.visto;
    }

    public void setVisto(boolean visto) {
        this.visto = visto;
    }

}
