package modelo;
// Generated May 18, 2016 12:59:04 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotificacionPasajero generated by hbm2java
 */
@Entity
@Table(name = "notificacion_pasajero", schema = "public"
)
public class NotificacionPasajero implements java.io.Serializable {

    private int idNotificacionp;
    private Pasajero pasajero;
    private String titulo;
    private String contenido;
    private Date fecha;
    private boolean visto;

    public NotificacionPasajero() {
    }

    public NotificacionPasajero(int idNotificacionp, Pasajero pasajero, String titulo, String contenido, Date fecha, boolean visto) {
        this.idNotificacionp = idNotificacionp;
        this.pasajero = pasajero;
        this.titulo = titulo;
        this.contenido = contenido;
        this.fecha = fecha;
        this.visto = visto;
    }

    @Id

    @Column(name = "id_notificacionp", unique = true, nullable = false)
    public int getIdNotificacionp() {
        return this.idNotificacionp;
    }

    public void setIdNotificacionp(int idNotificacionp) {
        this.idNotificacionp = idNotificacionp;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pasajero", nullable = false)
    public Pasajero getPasajero() {
        return this.pasajero;
    }

    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }

    @Column(name = "titulo", nullable = false, length = 64)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "contenido", nullable = false, length = 256)
    public String getContenido() {
        return this.contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 29)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "visto", nullable = false)
    public boolean isVisto() {
        return this.visto;
    }

    public void setVisto(boolean visto) {
        this.visto = visto;
    }

}
