package modelo;
// Generated 11/04/2016 03:54:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pasajero generated by hbm2java
 */
public class Pasajero  implements java.io.Serializable {


     private int idPasajero;
     private String pnombre;
     private String papp;
     private String papm;
     private String pcorreo;
     private String pnoCuenta;
     private Date pfechaNac;
     private String pcontrasenia;
     private Set pasajeroRutas = new HashSet(0);
     private Set perfilPasajeros = new HashSet(0);

    public Pasajero() {
    }

	
    public Pasajero(int idPasajero, String pnombre, String papp, String papm, String pcorreo, String pnoCuenta, Date pfechaNac, String pcontrasenia) {
        this.idPasajero = idPasajero;
        this.pnombre = pnombre;
        this.papp = papp;
        this.papm = papm;
        this.pcorreo = pcorreo;
        this.pnoCuenta = pnoCuenta;
        this.pfechaNac = pfechaNac;
        this.pcontrasenia = pcontrasenia;
    }
    public Pasajero(int idPasajero, String pnombre, String papp, String papm, String pcorreo, String pnoCuenta, Date pfechaNac, String pcontrasenia, Set pasajeroRutas, Set perfilPasajeros) {
       this.idPasajero = idPasajero;
       this.pnombre = pnombre;
       this.papp = papp;
       this.papm = papm;
       this.pcorreo = pcorreo;
       this.pnoCuenta = pnoCuenta;
       this.pfechaNac = pfechaNac;
       this.pcontrasenia = pcontrasenia;
       this.pasajeroRutas = pasajeroRutas;
       this.perfilPasajeros = perfilPasajeros;
    }
   
    public int getIdPasajero() {
        return this.idPasajero;
    }
    
    public void setIdPasajero(int idPasajero) {
        this.idPasajero = idPasajero;
    }
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }
    public String getPapp() {
        return this.papp;
    }
    
    public void setPapp(String papp) {
        this.papp = papp;
    }
    public String getPapm() {
        return this.papm;
    }
    
    public void setPapm(String papm) {
        this.papm = papm;
    }
    public String getPcorreo() {
        return this.pcorreo;
    }
    
    public void setPcorreo(String pcorreo) {
        this.pcorreo = pcorreo;
    }
    public String getPnoCuenta() {
        return this.pnoCuenta;
    }
    
    public void setPnoCuenta(String pnoCuenta) {
        this.pnoCuenta = pnoCuenta;
    }
    public Date getPfechaNac() {
        return this.pfechaNac;
    }
    
    public void setPfechaNac(Date pfechaNac) {
        this.pfechaNac = pfechaNac;
    }
    public String getPcontrasenia() {
        return this.pcontrasenia;
    }
    
    public void setPcontrasenia(String pcontrasenia) {
        this.pcontrasenia = pcontrasenia;
    }
    public Set getPasajeroRutas() {
        return this.pasajeroRutas;
    }
    
    public void setPasajeroRutas(Set pasajeroRutas) {
        this.pasajeroRutas = pasajeroRutas;
    }
    public Set getPerfilPasajeros() {
        return this.perfilPasajeros;
    }
    
    public void setPerfilPasajeros(Set perfilPasajeros) {
        this.perfilPasajeros = perfilPasajeros;
    }




}


