package modelo;
// Generated May 16, 2016 1:45:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pasajero generated by hbm2java
 */
@Entity
@Table(name="pasajero"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="pcorreo"), @UniqueConstraint(columnNames="pno_cuenta")} 
)
public class Pasajero  implements java.io.Serializable {


     private int idPasajero;
     private String pnombre;
     private String papp;
     private String papm;
     private String pcorreo;
     private String pnoCuenta;
     private Date pfechaNac;
     private String pcontrasenia;
     private Set calificacionChofers = new HashSet(0);
     private Set pasajeroRutas = new HashSet(0);
     private Set mensajePasajeros = new HashSet(0);
     private Set mensajeChofers = new HashSet(0);
     private Set solicituds = new HashSet(0);
     private Set perfilPasajeros = new HashSet(0);
     private Set calificacionPasajeros = new HashSet(0);

    public Pasajero() {
    }

	
    public Pasajero(int idPasajero, String pnombre, String papp, String papm, String pcorreo, String pnoCuenta, Date pfechaNac, String pcontrasenia) {
        this.idPasajero = idPasajero;
        this.pnombre = pnombre;
        this.papp = papp;
        this.papm = papm;
        this.pcorreo = pcorreo;
        this.pnoCuenta = pnoCuenta;
        this.pfechaNac = pfechaNac;
        this.pcontrasenia = pcontrasenia;
    }
    public Pasajero(int idPasajero, String pnombre, String papp, String papm, String pcorreo, String pnoCuenta, Date pfechaNac, String pcontrasenia, Set calificacionChofers, Set pasajeroRutas, Set mensajePasajeros, Set mensajeChofers, Set solicituds, Set perfilPasajeros, Set calificacionPasajeros) {
       this.idPasajero = idPasajero;
       this.pnombre = pnombre;
       this.papp = papp;
       this.papm = papm;
       this.pcorreo = pcorreo;
       this.pnoCuenta = pnoCuenta;
       this.pfechaNac = pfechaNac;
       this.pcontrasenia = pcontrasenia;
       this.calificacionChofers = calificacionChofers;
       this.pasajeroRutas = pasajeroRutas;
       this.mensajePasajeros = mensajePasajeros;
       this.mensajeChofers = mensajeChofers;
       this.solicituds = solicituds;
       this.perfilPasajeros = perfilPasajeros;
       this.calificacionPasajeros = calificacionPasajeros;
    }
   
     @Id 

    
    @Column(name="id_pasajero", unique=true, nullable=false)
    public int getIdPasajero() {
        return this.idPasajero;
    }
    
    public void setIdPasajero(int idPasajero) {
        this.idPasajero = idPasajero;
    }

    
    @Column(name="pnombre", nullable=false, length=64)
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }

    
    @Column(name="papp", nullable=false, length=64)
    public String getPapp() {
        return this.papp;
    }
    
    public void setPapp(String papp) {
        this.papp = papp;
    }

    
    @Column(name="papm", nullable=false, length=64)
    public String getPapm() {
        return this.papm;
    }
    
    public void setPapm(String papm) {
        this.papm = papm;
    }

    
    @Column(name="pcorreo", unique=true, nullable=false, length=128)
    public String getPcorreo() {
        return this.pcorreo;
    }
    
    public void setPcorreo(String pcorreo) {
        this.pcorreo = pcorreo;
    }

    
    @Column(name="pno_cuenta", unique=true, nullable=false, length=9)
    public String getPnoCuenta() {
        return this.pnoCuenta;
    }
    
    public void setPnoCuenta(String pnoCuenta) {
        this.pnoCuenta = pnoCuenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pfecha_nac", nullable=false, length=13)
    public Date getPfechaNac() {
        return this.pfechaNac;
    }
    
    public void setPfechaNac(Date pfechaNac) {
        this.pfechaNac = pfechaNac;
    }

    
    @Column(name="pcontrasenia", nullable=false, length=128)
    public String getPcontrasenia() {
        return this.pcontrasenia;
    }
    
    public void setPcontrasenia(String pcontrasenia) {
        this.pcontrasenia = pcontrasenia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set getCalificacionChofers() {
        return this.calificacionChofers;
    }
    
    public void setCalificacionChofers(Set calificacionChofers) {
        this.calificacionChofers = calificacionChofers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set getPasajeroRutas() {
        return this.pasajeroRutas;
    }
    
    public void setPasajeroRutas(Set pasajeroRutas) {
        this.pasajeroRutas = pasajeroRutas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set getMensajePasajeros() {
        return this.mensajePasajeros;
    }
    
    public void setMensajePasajeros(Set mensajePasajeros) {
        this.mensajePasajeros = mensajePasajeros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set getMensajeChofers() {
        return this.mensajeChofers;
    }
    
    public void setMensajeChofers(Set mensajeChofers) {
        this.mensajeChofers = mensajeChofers;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="pasajero")
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="pasajero")
    public Set getPerfilPasajeros() {
        return this.perfilPasajeros;
    }
    
    public void setPerfilPasajeros(Set perfilPasajeros) {
        this.perfilPasajeros = perfilPasajeros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasajero")
    public Set getCalificacionPasajeros() {
        return this.calificacionPasajeros;
    }
    
    public void setCalificacionPasajeros(Set calificacionPasajeros) {
        this.calificacionPasajeros = calificacionPasajeros;
    }




}


