package modelo;
// Generated 10-abr-2016 14:40:20 by Hibernate Tools 4.3.1



/**
 * PasajeroRutaId generated by hbm2java
 */
public class PasajeroRutaId  implements java.io.Serializable {


     private int idPasajero;
     private int idRuta;

    public PasajeroRutaId() {
    }

    public PasajeroRutaId(int idPasajero, int idRuta) {
       this.idPasajero = idPasajero;
       this.idRuta = idRuta;
    }
   
    public int getIdPasajero() {
        return this.idPasajero;
    }
    
    public void setIdPasajero(int idPasajero) {
        this.idPasajero = idPasajero;
    }
    public int getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(int idRuta) {
        this.idRuta = idRuta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PasajeroRutaId) ) return false;
		 PasajeroRutaId castOther = ( PasajeroRutaId ) other; 
         
		 return (this.getIdPasajero()==castOther.getIdPasajero())
 && (this.getIdRuta()==castOther.getIdRuta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPasajero();
         result = 37 * result + this.getIdRuta();
         return result;
   }   


}


