package modelo;
// Generated 11/04/2016 03:54:24 PM by Hibernate Tools 4.3.1



/**
 * PasajeroRuta generated by hbm2java
 */
public class PasajeroRuta  implements java.io.Serializable {


     private PasajeroRutaId id;
     private Pasajero pasajero;
     private Ruta ruta;
     private int dia;

    public PasajeroRuta() {
    }

    public PasajeroRuta(PasajeroRutaId id, Pasajero pasajero, Ruta ruta, int dia) {
       this.id = id;
       this.pasajero = pasajero;
       this.ruta = ruta;
       this.dia = dia;
    }
   
    public PasajeroRutaId getId() {
        return this.id;
    }
    
    public void setId(PasajeroRutaId id) {
        this.id = id;
    }
    public Pasajero getPasajero() {
        return this.pasajero;
    }
    
    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public int getDia() {
        return this.dia;
    }
    
    public void setDia(int dia) {
        this.dia = dia;
    }




}


