package modelo;
// Generated May 7, 2016 1:06:44 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PerfilPasajero generated by hbm2java
 */
@Entity
@Table(name = "perfil_pasajero", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id_pasajero")
)
public class PerfilPasajero implements java.io.Serializable {

    private int idPpasajero;
    private Pasajero pasajero;
    private String pfoto;
    private String psobreMi;
    private Boolean pestado;
    private Date fechaCreacion;

    public PerfilPasajero() {
    }

    public PerfilPasajero(int idPpasajero, Pasajero pasajero, Date fechaCreacion) {
        this.idPpasajero = idPpasajero;
        this.pasajero = pasajero;
        this.fechaCreacion = fechaCreacion;
    }

    public PerfilPasajero(int idPpasajero, Pasajero pasajero, String pfoto, String psobreMi, Boolean pestado, Date fechaCreacion) {
        this.idPpasajero = idPpasajero;
        this.pasajero = pasajero;
        this.pfoto = pfoto;
        this.psobreMi = psobreMi;
        this.pestado = pestado;
        this.fechaCreacion = fechaCreacion;
    }

    @Id

    @Column(name = "id_ppasajero", unique = true, nullable = false)
    public int getIdPpasajero() {
        return this.idPpasajero;
    }

    public void setIdPpasajero(int idPpasajero) {
        this.idPpasajero = idPpasajero;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pasajero", unique = true, nullable = false)
    public Pasajero getPasajero() {
        return this.pasajero;
    }

    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }

    @Column(name = "pfoto", length = 256)
    public String getPfoto() {
        return this.pfoto;
    }

    public void setPfoto(String pfoto) {
        this.pfoto = pfoto;
    }

    @Column(name = "psobre_mi", length = 256)
    public String getPsobreMi() {
        return this.psobreMi;
    }

    public void setPsobreMi(String psobreMi) {
        this.psobreMi = psobreMi;
    }

    @Column(name = "pestado")
    public Boolean getPestado() {
        return this.pestado;
    }

    public void setPestado(Boolean pestado) {
        this.pestado = pestado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_creacion", nullable = false, length = 29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

}
