package modelo;
// Generated 11/04/2016 03:54:24 PM by Hibernate Tools 4.3.1



/**
 * PerfilChofer generated by hbm2java
 */
public class PerfilChofer  implements java.io.Serializable {


     private int idPchofer;
     private Chofer chofer;
     private String foto;
     private String sobreMi;
     private Boolean estado;

    public PerfilChofer() {
    }

	
    public PerfilChofer(Chofer chofer) {
        this.chofer = chofer;
    }
    public PerfilChofer(Chofer chofer, String foto, String sobreMi, Boolean estado) {
       this.chofer = chofer;
       this.foto = foto;
       this.sobreMi = sobreMi;
       this.estado = estado;
    }
   
    public int getIdPchofer() {
        return this.idPchofer;
    }
    
    public void setIdPchofer(int idPchofer) {
        this.idPchofer = idPchofer;
    }
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getSobreMi() {
        return this.sobreMi;
    }
    
    public void setSobreMi(String sobreMi) {
        this.sobreMi = sobreMi;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


