package modelo;
// Generated May 4, 2016 9:25:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * PerfilPasajero generated by hbm2java
 */
public class PerfilPasajero implements java.io.Serializable {

    private int idPpasajero;
    private Pasajero pasajero;
    private String pfoto;
    private String psobreMi;
    private Boolean pestado;
    private Date fechaCreacion;

    public PerfilPasajero() {
    }

    public PerfilPasajero(int idPpasajero, Pasajero pasajero, Date fechaCreacion) {
        this.idPpasajero = idPpasajero;
        this.pasajero = pasajero;
        this.fechaCreacion = fechaCreacion;
    }

    public PerfilPasajero(int idPpasajero, Pasajero pasajero, String pfoto, String psobreMi, Boolean pestado, Date fechaCreacion) {
        this.idPpasajero = idPpasajero;
        this.pasajero = pasajero;
        this.pfoto = pfoto;
        this.psobreMi = psobreMi;
        this.pestado = pestado;
        this.fechaCreacion = fechaCreacion;
    }

    public int getIdPpasajero() {
        return this.idPpasajero;
    }

    public void setIdPpasajero(int idPpasajero) {
        this.idPpasajero = idPpasajero;
    }

    public Pasajero getPasajero() {
        return this.pasajero;
    }

    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }

    public String getPfoto() {
        return this.pfoto;
    }

    public void setPfoto(String pfoto) {
        this.pfoto = pfoto;
    }

    public String getPsobreMi() {
        return this.psobreMi;
    }

    public void setPsobreMi(String psobreMi) {
        this.psobreMi = psobreMi;
    }

    public Boolean getPestado() {
        return this.pestado;
    }

    public void setPestado(Boolean pestado) {
        this.pestado = pestado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

}
