package modelo;
// Generated May 16, 2016 1:45:53 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PerfilChofer generated by hbm2java
 */
@Entity
@Table(name = "perfil_chofer", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = "clave"),
    @UniqueConstraint(columnNames = "id_chofer")}
)
public class PerfilChofer implements java.io.Serializable {

    private int idPchofer;
    private Chofer chofer;
    private Imagen imagen;
    private String csobreMi;
    private Boolean cestado;
    private Date fechaCreacion;
    private String clave;

    public PerfilChofer() {
    }

    public PerfilChofer(int idPchofer, Chofer chofer, Date fechaCreacion) {
        this.idPchofer = idPchofer;
        this.chofer = chofer;
        this.fechaCreacion = fechaCreacion;
    }

    public PerfilChofer(int idPchofer, Chofer chofer, Imagen imagen, String csobreMi, Boolean cestado, Date fechaCreacion, String clave) {
        this.idPchofer = idPchofer;
        this.chofer = chofer;
        this.imagen = imagen;
        this.csobreMi = csobreMi;
        this.cestado = cestado;
        this.fechaCreacion = fechaCreacion;
        this.clave = clave;
    }

    @Id

    @Column(name = "id_pchofer", unique = true, nullable = false)
    public int getIdPchofer() {
        return this.idPchofer;
    }

    public void setIdPchofer(int idPchofer) {
        this.idPchofer = idPchofer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_chofer", unique = true, nullable = false)
    public Chofer getChofer() {
        return this.chofer;
    }

    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cfoto")
    public Imagen getImagen() {
        return this.imagen;
    }

    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }

    @Column(name = "csobre_mi", length = 256)
    public String getCsobreMi() {
        return this.csobreMi;
    }

    public void setCsobreMi(String csobreMi) {
        this.csobreMi = csobreMi;
    }

    @Column(name = "cestado")
    public Boolean getCestado() {
        return this.cestado;
    }

    public void setCestado(Boolean cestado) {
        this.cestado = cestado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_creacion", nullable = false, length = 29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Column(name = "clave", unique = true, length = 32)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

}
