package modelo;
// Generated May 4, 2016 9:25:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta implements java.io.Serializable {

    private int idRuta;
    private Automovil automovil;
    private String mapa;
    private String descripcion;
    private boolean activa;
    private Date fechaCreacion;
    private Set pasajeroRutas = new HashSet(0);
    private Set horarios = new HashSet(0);
    private Set solicituds = new HashSet(0);

    public Ruta() {
    }

    public Ruta(int idRuta, Automovil automovil, String mapa, boolean activa, Date fechaCreacion) {
        this.idRuta = idRuta;
        this.automovil = automovil;
        this.mapa = mapa;
        this.activa = activa;
        this.fechaCreacion = fechaCreacion;
    }

    public Ruta(int idRuta, Automovil automovil, String mapa, String descripcion, boolean activa, Date fechaCreacion, Set pasajeroRutas, Set horarios, Set solicituds) {
        this.idRuta = idRuta;
        this.automovil = automovil;
        this.mapa = mapa;
        this.descripcion = descripcion;
        this.activa = activa;
        this.fechaCreacion = fechaCreacion;
        this.pasajeroRutas = pasajeroRutas;
        this.horarios = horarios;
        this.solicituds = solicituds;
    }

    public int getIdRuta() {
        return this.idRuta;
    }

    public void setIdRuta(int idRuta) {
        this.idRuta = idRuta;
    }

    public Automovil getAutomovil() {
        return this.automovil;
    }

    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }

    public String getMapa() {
        return this.mapa;
    }

    public void setMapa(String mapa) {
        this.mapa = mapa;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public boolean isActiva() {
        return this.activa;
    }

    public void setActiva(boolean activa) {
        this.activa = activa;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Set getPasajeroRutas() {
        return this.pasajeroRutas;
    }

    public void setPasajeroRutas(Set pasajeroRutas) {
        this.pasajeroRutas = pasajeroRutas;
    }

    public Set getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }

    public Set getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }

}
