package modelo;
// Generated May 7, 2016 1:06:44 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ruta generated by hbm2java
 */
@Entity
@Table(name = "ruta", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id_automovil")
)
public class Ruta implements java.io.Serializable {

    private int idRuta;
    private Automovil automovil;
    private String mapa;
    private String descripcion;
    private boolean activa;
    private Date fechaCreacion;
    private Set pasajeroRutas = new HashSet(0);
    private Set horarios = new HashSet(0);
    private Set solicituds = new HashSet(0);

    public Ruta() {
    }

    public Ruta(int idRuta, Automovil automovil, String mapa, boolean activa, Date fechaCreacion) {
        this.idRuta = idRuta;
        this.automovil = automovil;
        this.mapa = mapa;
        this.activa = activa;
        this.fechaCreacion = fechaCreacion;
    }

    public Ruta(int idRuta, Automovil automovil, String mapa, String descripcion, boolean activa, Date fechaCreacion, Set pasajeroRutas, Set horarios, Set solicituds) {
        this.idRuta = idRuta;
        this.automovil = automovil;
        this.mapa = mapa;
        this.descripcion = descripcion;
        this.activa = activa;
        this.fechaCreacion = fechaCreacion;
        this.pasajeroRutas = pasajeroRutas;
        this.horarios = horarios;
        this.solicituds = solicituds;
    }

    @Id

    @Column(name = "id_ruta", unique = true, nullable = false)
    public int getIdRuta() {
        return this.idRuta;
    }

    public void setIdRuta(int idRuta) {
        this.idRuta = idRuta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_automovil", unique = true, nullable = false)
    public Automovil getAutomovil() {
        return this.automovil;
    }

    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }

    @Column(name = "mapa", nullable = false, length = 512)
    public String getMapa() {
        return this.mapa;
    }

    public void setMapa(String mapa) {
        this.mapa = mapa;
    }

    @Column(name = "descripcion", length = 120)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "activa", nullable = false)
    public boolean isActiva() {
        return this.activa;
    }

    public void setActiva(boolean activa) {
        this.activa = activa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_creacion", nullable = false, length = 29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ruta")
    public Set getPasajeroRutas() {
        return this.pasajeroRutas;
    }

    public void setPasajeroRutas(Set pasajeroRutas) {
        this.pasajeroRutas = pasajeroRutas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ruta")
    public Set getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ruta")
    public Set getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }

}
