ALTER TABLE CHOFER ADD CONSTRAINT CNO_CUENTA_CONS CHECK (LENGTH(CNO_CUENTA) = 9);

ALTER TABLE CHOFER ADD CONSTRAINT CNO_CUENTA_CONS2 CHECK (CNO_CUENTA ~ '^[0-9]+$');

ALTER TABLE CHOFER ADD CONSTRAINT CCORREO_CONS CHECK (CCORREO ~ '^[A-Za-z0-9._''-]+@ciencias.unam.mx');

ALTER TABLE AUTOMOVIL ADD CONSTRAINT CNO_PLACA_CONS CHECK (UPPER(PLACA) ~ '[0-9A-Z][0-9][0-9]-[A-Z][A-Z][A-Z]');

ALTER TABLE AUTOMOVIL ADD CONSTRAINT CAPACIDAD_CONS CHECK (CAPACIDAD > 0);

ALTER TABLE PASAJERO ADD CONSTRAINT PNO_CUENTA_CONS CHECK (LENGTH(PNO_CUENTA) = 9);

ALTER TABLE PASAJERO ADD CONSTRAINT PNO_CUENTA_CONS2 CHECK (PNO_CUENTA ~ '^[0-9]+$');

ALTER TABLE PASAJERO ADD CONSTRAINT PCORREO_CONS CHECK (PCORREO ~ '^[A-Za-z0-9._''-]+@ciencias.unam.mx');

CREATE EXTENSION IF NOT EXISTS unaccent;

ALTER TABLE PASAJERO_RUTA ADD CONSTRAINT DIA_CONS_PAS CHECK (UNACCENT(UPPER(DIA)) IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO'));

ALTER TABLE SOLICITUD ADD CONSTRAINT DIA_CONS_SOL CHECK (UNACCENT(UPPER(DIA)) IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO'));

ALTER TABLE CALIFICACION_CHOFER ADD CONSTRAINT CALIF_CHOFER_CONS CHECK (CALIFICACION >= 0 AND CALIFICACION <= 10);

ALTER TABLE CALIFICACION_PASAJERO ADD CONSTRAINT CALIF_PASAJERO_CONS CHECK (CALIFICACION >= 0 AND CALIFICACION <= 10);

ALTER TABLE CALIFICACION_CHOFER ADD CONSTRAINT CALIF_CHOFER_UNQ UNIQUE(ID_PASAJERO,ID_CHOFER);

ALTER TABLE CALIFICACION_PASAJERO ADD CONSTRAINT CALIF_PASAJERO_UNQ UNIQUE(ID_PASAJERO,ID_CHOFER);
