ALTER TABLE CHOFER ADD CONSTRAINT CNO_CUENTA_CONS CHECK (LENGTH(CNO_CUENTA) = 9);

ALTER TABLE CHOFER ADD CONSTRAINT CNO_CUENTA_CONS2 CHECK (CNO_CUENTA ~ '^[0-9]+$');

ALTER TABLE CHOFER ADD CONSTRAINT CCORREO_CONS CHECK (CCORREO ~ '^[A-Za-z0-9._%-]+@ciencias.unam.mx');

ALTER TABLE AUTOMOVIL ADD CONSTRAINT CNO_PLACA_CONS CHECK (UPPER(PLACA) ~ '[0-9][0-9][0-9][A-Z][A-Z][A-Z]');

ALTER TABLE HORARIO ADD CONSTRAINT LUNES_CONS CHECK (LUNES >= 0 AND LUNES < 24);

ALTER TABLE HORARIO ADD CONSTRAINT MARTES_CONS CHECK (MARTES >= 0 AND MARTES < 24);

ALTER TABLE HORARIO ADD CONSTRAINT MIERCOLES_CONS CHECK (MIERCOLES >= 0 AND MIERCOLES < 24);

ALTER TABLE HORARIO ADD CONSTRAINT JUEVES_CONS CHECK (JUEVES >= 0 AND JUEVES < 24);

ALTER TABLE HORARIO ADD CONSTRAINT VIERNES_CONS CHECK (VIERNES >= 0 AND VIERNES < 24);

ALTER TABLE HORARIO ADD CONSTRAINT SABADO_CONS CHECK (SABADO >= 0 AND SABADO < 24);

ALTER TABLE PASAJERO ADD CONSTRAINT PNO_CUENTA_CONS CHECK (LENGTH(PNO_CUENTA) = 9);

ALTER TABLE PASAJERO ADD CONSTRAINT PNO_CUENTA_CONS2 CHECK (PNO_CUENTA ~ '^[0-9]+$');

ALTER TABLE PASAJERO ADD CONSTRAINT PCORREO_CONS CHECK (PCORREO ~ '^[A-Za-z0-9._%-]+@ciencias.unam.mx');

ALTER TABLE PASAJERO_RUTA ADD CONSTRAINT DIA_CONS CHECK (DIA > 0 AND DIA < 8);

ALTER TABLE PERFIL_PASAJERO ALTER COLUMN PFOTO SET DEFAULT 'resources/imagenes/foto_usuario/usuario.png';

ALTER TABLE PERFIL_CHOFER ALTER COLUMN CFOTO SET DEFAULT 'resources/imagenes/foto_usuario/usuario.png';
